### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [Tetr4/CompassTile#1]
Are there any plans to make your app available outside of Google's PlayStore – for those without access to that walled garden? Maybe e.g. attaching the APK file to [Releases](https://github.com/Tetr4/CompassTile/releases) here? Thanks in advance!

**Comment by Tetr4** [comment]
Good idea, here you go: https://github.com/Tetr4/CompassTile/releases

Maybe I will check, if I can deploy to F-Droid. No promises though 🙂

**Comment by IzzySoft** [comment]
> Good idea, here you go:

Thanks a lot!

> Maybe I will check, if I can deploy to F-Droid. No promises though 🙂

No promises needed, if you're happy having your app at IzzyOnDroid, [where it will show up](https://apt.izzysoft.de/packages/de.klimek.compass/) in about an hour (with the next sync at around 6 pm UTC). To give you a "sneak preview":

![image](https://github.com/Tetr4/CompassTile/assets/6781438/657a9ecd-ffde-4e91-b391-9362e73d36b9)
![image](https://github.com/Tetr4/CompassTile/assets/6781438/07a476be-3fa9-456e-b18a-7875f1c36ddd)

One small finding by the scanners I want to mention:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided by a small change in your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

PS: Should you want to go for a listing with F-Droid.org, feel free to give me a ping to provide you with the Fastlane metadata structure they will ask for. Ah, forget the condition: just give me a ping if you want that. It would give you the power to define how your listing looks like, by providing descriptions and graphics in a format that can automatically be processed; it's used by IzzyOnDroid as well. For more details and guidelines on this, be welcome to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). Both, F-Droid and IzzyOnDroid, would just need the metadata, no need to install/use the fastlane binaries.

That said: welcome aboard :smiley:
