### ISSUE TITLE
Icon Points In Wrong Direction

### ISSUE THREAD

**Issue by user44000** [Tetr4/CompassTile#2]
The icon is pointing in the wrong direction. 
![Screenshot_20240614-163237_FOSS Browser_1](https://github.com/Tetr4/CompassTile/assets/138707369/49b14f53-4f41-4119-8e84-259dd32de38c)

**Comment by Tetr4** [comment]
Hi, the little marker on the needle is pointing towards north. I guess it is a bit open to interpretation. Here is an image with that part of the needle colored in red:

![Compass Stock Image](https://as1.ftcdn.net/v2/jpg/04/02/19/44/1000_F_402194485_MAIHKNWL53EKL8fSCs8mj91VZ2wXgv5t.jpg)

You are heading north east (53°), so north should be on your left side.
